Parameters:
  DBNameParam: 
    Type: String
  MUserParam:
    Type: String
  MUserPasswordParam:
    Type: String
    Description: "It must be longer than 8 characters"
Resources:
  MyFirstDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBNameParam
      MasterUsername: !Ref MUserParam
      MasterUserPassword: !Ref MUserPasswordParam
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PubliclyAccessible: True
      AllocatedStorage: 20
      DBInstanceIdentifier: !Join ["-in-", ["DatabaseLevelUp-MySql-Instance", !Ref "AWS::Region"]] 
      Tags: 
      - Key: "owner"
        Value: "anza@bbd.co.za"
      - Key: "created-using"
        Value: "cloudformation"