Metadata:
  AWS::CloudFormation::Stack:
    Tags:
      - Key: "owner"
        Value: "anza@bbd.co.za"
      - Key: "created-using"
        Value: "cloudformation"

Parameters:
  DBNameParam: 
    Type: String
  MUserParam:
    Type: String
  MUserPasswordParam:
    Type: String
    Description: "It must be longer than 8 characters"

Resources:
  DBInstanceVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: "default"
      Tags:
      - Key: "owner"
        Value: "anza@bbd.co.za"
      - Key: "created-using"
        Value: "cloudformation"

  DBInstanceSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DBInstanceVPC
      CidrBlock: "10.0.1.0/24"
      Tags:
      - Key: "owner"
        Value: "anza@bbd.co.za"
      - Key: "created-using"
        Value: "cloudformation"
  
  # DBInstanceSubnet2:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref DBInstanceVPC
  #     CidrBlock: "10.0.2.0/24"
  #     AvailabilityZone: "eu-west-1b"
  #     Tags:
  #     - Key: "owner"
  #       Value: "anza@bbd.co.za"
  #     - Key: "created-using"
  #       Value: "cloudformation"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: "DBInstanceSubnetGroup"
      DBSubnetGroupDescription: "Subnet group for RDS instance"
      SubnetIds:
        - !Ref DBInstanceSubnet
        # - !Ref DBInstanceSubnet2

  DBInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for RDS instance"
      VpcId: !Ref DBInstanceVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: "0.0.0.0/0"
      Tags:
      - Key: "owner"
        Value: "anza@bbd.co.za"
      - Key: "created-using"
        Value: "cloudformation"

  MySqlDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBNameParam
      MasterUsername: !Ref MUserParam
      MasterUserPassword: !Ref MUserPasswordParam
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      # DBSecurityGroups: !Ref DBInstanceSecurityGroup
      VPCSecurityGroups: 
        - !GetAtt DBInstanceSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      StorageType: gp2
      PubliclyAccessible: True
      AllocatedStorage: 20
      DBInstanceIdentifier: !Join ["-in-", ["DatabaseLevelUp-MySql-Instance", !Ref "AWS::Region"]]
      MultiAZ: False
      Tags: 
      - Key: "owner"
        Value: "anza@bbd.co.za"
      - Key: "created-using"
        Value: "cloudformation"
    