Metadata:
  AWS::CloudFormation::Stack:
    Tags:
      - Key: "owner"
        Value: "anza@bbd.co.za"
      - Key: "created-using"
        Value: "cloudformation"

Parameters:
  DBNameParam: 
    Type: String
  MUserParam:
    Type: String
  MUserPasswordParam:
    Type: String
    Description: "It must be longer than 8 characters"
Resources:

  