
name: Database Migration Tests with Flyway

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/database/migrations/**'

  workflow_dispatch:

jobs:
  test-migrations:
    name: Test flyway migration scripts
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: install snapd
        run: sudo apt install snapd
      - name: Install Flyway 
        run: sudo snap install flyway
      - name: Run flyway
        run: flyway migrate
      # - uses: actions/checkout/@v2
      # - name: Test migrations on Flyway Hub
      #   uses: red-gate/flyway-hub-migration-test@v4
      #   with:
      #     projectName: databases-levelup
      #     engine: postgres-13
      #     migrationDirs: src/database/migrations 
      #     flywayConfPath: flyway.conf  
env:
  FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}
