
name: Database Migration Tests with Flyway

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/database/migrations/**'

  workflow_dispatch:

jobs:
  test-migrations:
    name: Test flyway migration scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3
      - name: Test migrations on Flyway Hub
        uses: red-gate/flyway-hub-migration-test@v4
        with:
          projectName: databases-levelup
          engine: postgres-16
          migrationDirs: src/database/migrations 
          flywayConfPath: flyway.conf  
env:
  FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}
