
name: Deploy CloudFormation Stack

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/infrastructure/cloudformation/rds_deploy.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/infrastructure/cloudformation/rds_deploy.yml'
  workflow_dispatch:

jobs:
  InfrastructureDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          role-session-name: ${{ vars.ROLE_SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update or Create CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ vars.CLOUDFORMATION_STACKNAME }}
          template: src/infrastructure/cloudformation/rds_deploy.yml
          parameter-overrides: "DBNameParam=${{ vars.DB_Name }},MUserPasswordParam=${{ secrets.DB_PASSWORD }},MUserParam=${{ vars.DB_USER }}"
